apprise:
  - discord://webhook_id/webhook_token
  - join://apikey/device
  - slack://TokenA/TokenB/TokenC/
  
reddit:
  client: xxxxxxxxxx
  secret: xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxx
  agent: reddit-post-notifier (u/xxxxxx)
    
  subreddits:
   gamedeals:
    include:
      - 'free'
      - '100%'
    exclude:
     - 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
     
   gundeals:
    include:
      - 'handgun'
      - '9mm'
    exclude:
     - 'Glock 19'
  
