version: "1.0"

services:
    redditmonitor:
        container_name: redditmonitor
        image: ghcr.io/jamessampsan/redditmonitor
        restart: unless-stopped
        volumes:
            - ./config.yaml:/app/config.yaml
